version: 0.2

env:
  # git認証情報ヘルパーを有効化##
  git-credential-helper: yes
  variables:
    ENV: "ut"
  # parameter-store:
  #   USER_NAME: "git-user-name"
  #   PAT: "git-pat"

phases:
  pre_build:
    commands:
      # タイムゾーンをJSTへ変換
      - export TZ="Asia/Tokyo"
      - echo $ENV
  # # リモートリポジトリ確認
  # - git remote -v
  # - git branch
      # ユーザー情報
      - git config --global user.email daiki.tomimori@japan-systems.co.jp
      - git config --global user.name "daiki tomimori"

  build:
    commands:
      # # developブランチをmasterブランチへマージ
      - git switch master
      - git merge -X theirs develop
      - git merge develop
      # # タグ付け
      # # TODO: CodePipelineのタグ情報から環境を取得する
      - TAG_NAME="v.${ENV}_$(date +%Y-%m-%d_%H%M)"
      - git tag $TAG_NAME
      - git push origin master
      - git push origin $TAG_NAME
