version: 0.2
 
env:
  variables:
    CLUSTER_NAME: "sa-ita-ecscls-test"
    SERVICE_NAME: "sa-ita-ecstaskdef-ecstaskdef-web-service-3pcbomrv"
    CONTAINER_PORT: 80
 
phases:
  install:
   commands:
      - cd ./Test
      - npm ci
      - npm install dotenv --save-dev
  pre_build:
    commands:
      - echo Getting ECS task IP...
      # タスクARN取得
      - TASK_ARN=$(aws ecs list-tasks --cluster $CLUSTER_NAME --service-name $SERVICE_NAME --query 'taskArns[0]' --output text)
      - echo "$TASK_ARN"
      # ENI取得
      - ENI_ID=$(aws ecs describe-tasks --cluster $CLUSTER_NAME --tasks $TASK_ARN --query 'tasks[0].attachments[0].details[?name==`networkInterfaceId`].value'  --output text)
      # プライベートIP取得
      # - PRIVATE_IP=$(aws ec2 describe-network-interfaces --network-interface-ids $ENI_ID --query 'NetworkInterfaces[0].PrivateIpAddress' --output text)
      # - echo "$PRIVATE_IP"
      # - echo "BASE_URL=http://$PRIVATE_IP" >> ./tests/.env
      # - cat ./tests/.env
      # パブリックIP取得
      - PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids $ENI_ID --query 'NetworkInterfaces[0].Association.PublicIp' --output text)
      - echo "$PUBLIC_IP"
      - echo "BASE_URL=http://$PUBLIC_IP" >> ./tests/.env
      - cat ./tests/.env
      - echo "ディレクトリ1"
      - pwd
      - ls -i
  build:
    commands:
      - echo Running Playwright tests...
      - echo "Contents of .env:"
      # - cd ./Test
      - echo "ディレクト2"
      - pwd
      - ls -i
      # - echo "Contents of .env:"
      # - cat .env
      - npx playwright install
      - npx playwright test
      # - cd ../
      # - cd ./playwright-report
      # - pwd
      # - ls -i
reports:
  playwright-reports:
    files:
      - Test/playwright-report/*.xml
    file-format: "JUNITXML" 
artifacts:
  files:
    - tests/reports/*
    - tests/tests/*
  name: $CODEBUILD_BUILD_NUMBER
 