# version: 0.2

# phases:
#   install:
#     commands:
#       # Testディレクトリ内のpackage.jsonの依存関係パッケージをインストール
#       - cd ./tests
#       - npm i
  
#   build:
#     commands:
#       # playwrightのテストを実施する
#       - npx playwright test

# # レポートの指定
# reports:
#   playwright-reports:
#     files:
#       - Test/reports/*.xml
#     file-format: "JUNITXML"

# # アーティファクトの指定
# artifacts:
#   files:
#     - Test/reports/*
#     - Test/tests/*
#   name: $CODEBUILD_BUILD_NUMBER

version: 0.2
 
env:
  variables:
    CLUSTER_NAME: "sa-ita-ecscls-test"
    SERVICE_NAME: "sa-ita-ecstaskdef-ecstaskdef-web-service-3pcbomrv"
    CONTAINER_PORT: 80
 
phases:
  install:
   commands:
      - cd ./tests
      - npm ci
  pre_build:
    commands:
      - echo Getting ECS task IP...
      # タスクARN取得
      - TASK_ARN=$(aws ecs list-tasks --cluster $CLUSTER_NAME --service-name $SERVICE_NAME --query 'taskArns[0]' --output text)
      # パブリックIP取得
      - PUBLIC_IP=$(aws ecs describe-tasks --cluster your-cluster --tasks $TASK_ARN --query 'tasks[0].containers[0].networkInterfaces[0].publicIpv4Address' --output text)
      - echo $PUBLIC_IP"
      - echo "BASE_URL=http://$PUBLIC_IP" >> $CODEBUILD_SRC_DIR/tests/.env
  build:
    commands:
      - echo Running Playwright tests...
      - cd ./tests
      - npx playwright install --with-deps
      - npx playwright test --project=chromium
reports:
  playwright-reports:
    files:
      - reports/*.xml
    file-format: "JUNITXML" 
artifacts:
  files:
    - tests/reports/*
    - tests/tests/*
  name: $CODEBUILD_BUILD_NUMBER
 